// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"
	"nft_auction_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			// 查询接口
			{
				Method:  http.MethodGet,
				Path:    "/api/price2usd/:tokenAddress/:amount",
				Handler: GetPrice2USDHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auctions",
				Handler: ListAuctionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auctions/:auctionId",
				Handler: GetAuctionHandler(serverCtx),
			},
			// 写操作接口
			{
				Method:  http.MethodPost,
				Path:    "/api/createAuction",
				Handler: CreateAuctionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/startAuction",
				Handler: StartAuctionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/endAuction",
				Handler: EndAuctionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/cancelAuction",
				Handler: CancelAuctionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/bidAuction",
				Handler: BidAuctionHandler(serverCtx),
			},
			// 配置接口
			{
				Method:  http.MethodPost,
				Path:    "/api/setPriceFeed",
				Handler: SetPriceFeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/version",
				Handler: GetVersionHandler(serverCtx),
			},
			// Mock 接口
			{
				Method:  http.MethodPost,
				Path:    "/api/mock/nft",
				Handler: MockNftHandler(serverCtx),
			},
		},
	)
}
